### ISSUE TITLE
Exception thrown when combining blazor-validation with radzen blazor dropdown component

### ISSUE THREAD

**Issue by adzhazhev** [mrpmorris/blazor-validation#12]
Hi Peter, thank for making this library. I've been enjoying it but I have encountered a weird issue.
I've been combining your validation with some components from Radzen. 

I want to mention that I believe that this isn't an issue with your lib exactly but I've been trying to get to bottom of this issue for some time and you might be my best chance, for engineering's sake :D You as an author of the library might be able to point me what's exactly going on, actually I believe you might be of the few people that might get what I am actually talking about at all.

I've raised the issue with the radzen team here: https://forum.radzen.com/t/radzendropdown-and-fluentvalidation-issues/2832 but they seem to be clueless. I'm giving the link so I don't write the same thing twice.

If you have some spare time please take a look. I'd really appreciate it.

**Comment by mrpmorris** [comment]
Have you tried `NotNull` before `IsInEnum`?

If that doesn't work, let me have a repo and I'll take a look.
