### ISSUE TITLE
ConfigurationExtension does not actually build a list of validators associated with a model.

### ISSUE THREAD

**Issue by rlebowitz** [mrpmorris/blazor-validation#14]
If I understand your code correctly, one of the purposes of the ValidationConfigurationFluentValidationExtensions is to determine ALL the types of validators that associated with particular entity Type.  You are storing the associated Validator Types in a List but from what I can tell, your code will only identify one Validator Type, the one associated with the entity model itself, but none of the validators that might be associated with the entity model's properties.  

I think that you have to walk the object graph to get all the validators involved.

**Comment by mrpmorris** [comment]
The validation profile for the class is supposed to create a rule for the member telling FluentValidation to use a specific validator.

Please correct me if I am wrong, but I believe that's how it works.
