### ISSUE TITLE
Upgrade FluentValidation to version 9.0.1

### ISSUE THREAD

**Issue by dodyg** [mrpmorris/blazor-validation#15]
I would have created a pull request for this unfortunately I have problem building the source code

**Comment by mrpmorris** [comment]
Oh, what problem are you having?

**Comment by dodyg** [comment]
![problems](https://user-images.githubusercontent.com/1761249/88199923-b6ce3b00-cc45-11ea-951b-e10686c8c907.png)

**Comment by mrpmorris** [comment]
Remove the signing in the project settings, that'll do it.

**Comment by mrpmorris** [comment]
Fixed in 1.4.0
