### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GioviQ** [mrpmorris/blazor-validation#17]
Hi,
I discovered your project because I read https://github.com/dotnet/aspnetcore/issues/23380

Currently DataAnnotations in Blazor do not support IStringLocalizer, so I tried to extend attributes, but I read there "Injecting services for validation is not a feature Blazor offers."

So I have a question:

despite localization not using IStringLocalizer,  DataAnnotations are working in Blazor, so I do not understand the purpose of https://github.com/mrpmorris/blazor-validation/tree/master/samples/01-DataAnnotationsValidation/

Thanks

**Comment by mrpmorris** [comment]
You can use multiple sources. So you could combine data annotation validation with fluent validation for checking a value is unique via a web api - or you could not bother with annotations at all and rely only on fluent validation - or you can add your own provider.
