### ISSUE TITLE
Error when Remove item of list child

### ISSUE THREAD

**Issue by QuocBV** [mrpmorris/blazor-validation#18]
Hi Team,
I have a error.
I have a list of modal.
Step 1:  Add an item (not valid by antotation) to list on front end 
Step 2: Click save and run editContext.ValidateObjectTree()  return false -> OK show error to front end
Step 3: Then I remove this item
Step 4:  Click save and  editContext.ValidateObjectTree() 
But  this return false and error 
When i get editContext.GetValidationMessages() This return msg error of deleted item
Please help me fix it

**Comment by mrpmorris** [comment]
Do any of the Editcontext methods help?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.editcontext?view=aspnetcore-3.1#methods

**Comment by Thnslj** [comment]
@mrpmorris I'm having the same issue, but can only reproduce in a WebAssembly project.

- Copy files from sample 2 to a new WebAssembly project.
- Add a `<ValidationSummary /> to samples/02-FluentValidation/FluentValidationSample/Pages/Index.razor 
- add Console.WriteLine(editContext.ValidateObjectTree()); to `void SubmitForm`
- Run the project
- Submit the form and verify errors from the summary
- Remove an address
- See that the summary still has errors from that address

**Comment by mrpmorris** [comment]
Unfortunately, there is no way for me to clear out existing error messages. You'll have to call editContext.Validate() before calling editContext.ValidateObjectTree
