### ISSUE TITLE
Can't run the samples, error signing output with public key

### ISSUE THREAD

**Issue by MrYossu** [mrpmorris/blazor-validation#23]
I just downloaded the source to look at the samples, but when I try to run, I get the following build error...

>Severity	Code	Description	Project	File	Line	Suppression State
>Error	CS7027	Error signing output with public key from file 'MrPMorris.snk' -- File not found.	PeterLeslieMorris.Blazor.Validation (netstandard2.1)	D:\blazor-validation-master\src\PeterLeslieMorris.Blazor.Validation\CSC	1	Active

Anyone able to advise? Thanks

**Comment by mrpmorris** [comment]
Go to the properties page for each project,  go to signing and remove the reference to my mrpmorris key.
