### ISSUE TITLE
How do we write unit tests against a validator?

### ISSUE THREAD

**Issue by MrYossu** [mrpmorris/blazor-validation#29]
Title pretty much says it all.

**Comment by mrpmorris** [comment]
bUnit would probably work.  I expect there are recommendations for testing FluentValidation on its own, if that is what you are using?

**Comment by MrYossu** [comment]
Ah, didn't occur to me that as your package is based on that, I could use their testing methods. Don't even need bUnit, as you can [test the validators directly](https://docs.fluentvalidation.net/en/latest/testing.html)

Thanks.
