### ISSUE TITLE
Validating IsValueType using ValidateObjectTree

### ISSUE THREAD

**Issue by freenetbrasil** [mrpmorris/blazor-validation#38]
Hi,

I've a struct similar to this:

```
public string Photo { get; set; }
public string Name { get; set; }
public string Last { get; set; }
public int? InfoInt { get; set; } = null;

```
On the submit button I've the following code:

```
void SubmitForm(EditContext editContext)
    {
        editContext.ValidateObjectTree();
    }

```
When I execute the ValidateObjectTree it doesn't validate the field 'InfoInt' which is 'int?', looking through the source code I found on 'EditContextExtensions.cs' on the 'ValidateProperty' method you check for this:

```
		if (property.PropertyType.IsValueType)
				return;

```
This prevent any integer validation, if I comment this out the validation works as planned.

Any special reason for this?  Can I safely comment this out? Any help is appreciated.

Thanks

**Comment by mrpmorris** [comment]
Any rules for ValueType properties should be added to the validator of the owning class.

Here is why that check was added. 
https://github.com/mrpmorris/blazor-validation/issues/28
