### ISSUE TITLE
Is there a way to validate to a database within the validator class?

### ISSUE THREAD

**Issue by ttaylor29** [mrpmorris/blazor-validation#41]
Hello!

Is there a way to call a database to validate something from fluent validation or your blazor validation?

**Comment by mrpmorris** [comment]
I would recommend doing that as an individual call to an api after the user leaves the input.

But if you want to do it anyway, you can do this....
https://github.com/mrpmorris/blazor-validation/tree/master/samples/02-FluentValidation/FluentValidationSample
